name: Weekly Meeting Reminder

on:
  schedule:
    # 毎週月曜日の朝9時（UTC）に実行（JST 18:00）
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # 手動実行も可能に

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        # 読み取り専用のアクセスを指定
        persist-credentials: false
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Send reminder
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        DEFAULT_CHANNEL: ${{ secrets.DEFAULT_CHANNEL }}
      run: |
        python main.py send_reminder