name: Weekly Meeting Reminder

on:
  schedule:
    # 毎週月曜日の朝9時（UTC）に実行。日本時間では18時
    - cron: '0 9 * * 1'
  workflow_dispatch:  # 手動実行用

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install slack_sdk flask
      
      - name: Run reminder script
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          DEFAULT_CHANNEL: ${{ secrets.DEFAULT_CHANNEL }}
        run: python main.py send_reminder
      
      - name: Commit changes to meeting data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add meeting_data.json
          git commit -m "Update meeting data" || echo "No changes to commit"
          git push